"""增加是否持有保安证字段

Revision ID: 00561a2375b2
Revises: 2c6bcac6aa31
Create Date: 2026-01-01 01:56:43.690080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00561a2375b2'
down_revision = '2c6bcac6aa31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employment_cycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_security_license', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employment_cycles', schema=None) as batch_op:
        batch_op.drop_column('has_security_license')

    # ### end Alembic commands ###
