"""增加队员扫码填资料

Revision ID: 11f326d747a4
Revises: 00561a2375b2
Create Date: 2026-01-01 04:47:37.674186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f326d747a4'
down_revision = '00561a2375b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employment_cycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_self_registered', sa.Boolean(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employment_cycles', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('is_self_registered')

    # ### end Alembic commands ###
