"""fix business trip schema

Revision ID: 1d1193ab9f93
Revises: 4393a28e9282
Create Date: 2026-01-14 17:39:48.989664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1193ab9f93'
down_revision = '4393a28e9282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_participants',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employment_cycles.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['business_trips.id'], ),
    sa.PrimaryKeyConstraint('trip_id', 'employee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_participants')
    op.drop_table('business_trips')
    # ### end Alembic commands ###
