"""数据库地址增加村级

Revision ID: 288a44f9cc94
Revises: d22b6646cd8f
Create Date: 2026-02-02 11:47:08.530668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288a44f9cc94'
down_revision = 'd22b6646cd8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employment_cycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('household_village', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('residence_village', sa.String(length=50), nullable=True))
        batch_op.alter_column('household_town',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('household_detail',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('residence_town',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('residence_detail',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employment_cycles', schema=None) as batch_op:
        batch_op.alter_column('residence_detail',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('residence_town',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('household_detail',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('household_town',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('residence_village')
        batch_op.drop_column('household_village')

    # ### end Alembic commands ###
