"""initial migration

Revision ID: 2c6bcac6aa31
Revises: 
Create Date: 2026-01-01 01:01:07.487547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6bcac6aa31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employment_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_card', sa.String(length=18), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=2), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('photo_path', sa.String(length=200), nullable=True),
    sa.Column('ethnic', sa.String(length=20), nullable=True),
    sa.Column('politics', sa.String(length=20), nullable=True),
    sa.Column('education', sa.String(length=20), nullable=True),
    sa.Column('household_province', sa.String(length=20), nullable=True),
    sa.Column('household_city', sa.String(length=20), nullable=True),
    sa.Column('household_district', sa.String(length=20), nullable=True),
    sa.Column('household_town', sa.String(length=20), nullable=True),
    sa.Column('household_detail', sa.String(length=100), nullable=True),
    sa.Column('residence_province', sa.String(length=20), nullable=True),
    sa.Column('residence_city', sa.String(length=20), nullable=True),
    sa.Column('residence_district', sa.String(length=20), nullable=True),
    sa.Column('residence_town', sa.String(length=20), nullable=True),
    sa.Column('residence_detail', sa.String(length=100), nullable=True),
    sa.Column('military_service', sa.Boolean(), nullable=True),
    sa.Column('enlistment_date', sa.Date(), nullable=True),
    sa.Column('unit_number', sa.String(length=50), nullable=True),
    sa.Column('branch', sa.String(length=50), nullable=True),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('has_license', sa.Boolean(), nullable=True),
    sa.Column('license_date', sa.Date(), nullable=True),
    sa.Column('license_type', sa.String(length=20), nullable=True),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('security_license_number', sa.String(length=50), nullable=True),
    sa.Column('security_license_date', sa.Date(), nullable=True),
    sa.Column('salary_mode', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('post', sa.String(length=20), nullable=True),
    sa.Column('emergency_name', sa.String(length=50), nullable=True),
    sa.Column('emergency_relation', sa.String(length=20), nullable=True),
    sa.Column('emergency_phone', sa.String(length=20), nullable=True),
    sa.Column('hat_size', sa.String(length=10), nullable=True),
    sa.Column('short_sleeve', sa.String(length=10), nullable=True),
    sa.Column('long_sleeve', sa.String(length=10), nullable=True),
    sa.Column('winter_uniform', sa.String(length=10), nullable=True),
    sa.Column('shoe_size', sa.String(length=10), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('is_room_leader', sa.Boolean(), nullable=True),
    sa.Column('bed_number', sa.String(length=50), nullable=True),
    sa.Column('archives', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employment_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employment_cycles_id_card'), ['id_card'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('module', 'action', name='uix_module_action')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('x_pos', sa.Integer(), nullable=True),
    sa.Column('y_pos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['employment_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_number'), ['number'], unique=True)

    op.create_table('shift_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('default_start', sa.String(length=10), nullable=True),
    sa.Column('default_end', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shift_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=18), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('allocated_quantity', sa.Integer(), nullable=True),
    sa.Column('photo_path', sa.String(length=200), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ownership', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('bed_capacity', sa.Integer(), nullable=True),
    sa.Column('current_user_id', sa.Integer(), nullable=True),
    sa.Column('allocation_mode', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_user_id'], ['employment_cycles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('funds_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('payer', sa.String(length=50), nullable=True),
    sa.Column('item', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedulings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('shift_type', sa.String(length=10), nullable=True),
    sa.Column('is_overtime', sa.Boolean(), nullable=True),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employment_cycles.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['shift_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('is_duty_leader', sa.Boolean(), nullable=True),
    sa.Column('is_duty_chief', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employment_cycles.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['shift_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_schedules_date'), ['date'], unique=False)

    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_id', name='uix_user_perm')
    )
    op.create_table('asset_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['employment_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('action_date', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['employment_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('sn_number', sa.String(length=100), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_check_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['employment_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_instances_sn_number'), ['sn_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_instances_sn_number'))

    op.drop_table('asset_instances')
    op.drop_table('asset_history')
    op.drop_table('asset_allocations')
    op.drop_table('user_permissions')
    with op.batch_alter_table('shift_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_schedules_date'))

    op.drop_table('shift_schedules')
    op.drop_table('schedulings')
    op.drop_table('operation_logs')
    op.drop_table('funds_records')
    op.drop_table('assets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('shift_templates')
    op.drop_table('shift_posts')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_number'))

    op.drop_table('rooms')
    op.drop_table('permissions')
    with op.batch_alter_table('employment_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employment_cycles_id_card'))

    op.drop_table('employment_cycles')
    # ### end Alembic commands ###
