"""删除排班无用表

Revision ID: 62491cb9669b
Revises: 81de1cf24548
Create Date: 2026-02-05 22:58:42.791846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62491cb9669b'
down_revision = '81de1cf24548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedulings')
    with op.batch_alter_table('shift_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('is_overtime', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_schedules', schema=None) as batch_op:
        batch_op.drop_column('hours')
        batch_op.drop_column('is_overtime')
        batch_op.drop_column('shift_type')

    op.create_table('schedulings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.Column('shift_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('is_overtime', sa.BOOLEAN(), nullable=True),
    sa.Column('hours', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employment_cycles.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['shift_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
