"""增加请假附件

Revision ID: 7f2083e84a80
Revises: 288a44f9cc94
Create Date: 2026-02-05 10:55:18.378485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2083e84a80'
down_revision = '288a44f9cc94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachments', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_records', schema=None) as batch_op:
        batch_op.drop_column('attachments')

    # ### end Alembic commands ###
