"""增加了资产子编号反向关联

Revision ID: cbc23843eb6b
Revises: 11f326d747a4
Create Date: 2026-01-01 16:10:27.077869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc23843eb6b'
down_revision = '11f326d747a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employment_cycles', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('is_self_registered')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employment_cycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_self_registered', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
