"""删除出差事由字段

Revision ID: cc5f78c5318d
Revises: c6018d7a767e
Create Date: 2026-01-14 20:22:01.265612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc5f78c5318d'
down_revision = 'c6018d7a767e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_trips', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
